#!/bin/python3

import math
import os
import random
import re
import sys

def diagonalDifference(arr):
    d1=0
    d2=0
    for i in range(len(arr)):
        d1+=arr[i][i]
        d2+=arr[i][len(arr)-i-1]
    diff=d1-d2
    if diff<0:
        diff=-diff
    return diff

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    arr = []

    for _ in range(n):
        arr.append(list(map(int, input().rstrip().split())))

    result = diagonalDifference(arr)

    fptr.write(str(result) + '\n')

    fptr.close()
