#!/bin/python3

import math
import os
import random
import re
import sys


def repeatedString(s, n):
    repeatTimes = n // len(s)
    remainingString = s[: n % len(s)]
    return s.count('a')*repeatTimes + remainingString.count('a')

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    n = int(input().strip())

    result = repeatedString(s, n)

    fptr.write(str(result) + '\n')

    fptr.close()
